postgres:
  aware:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
      max-active: 50
      initial-size: 5
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validationQuery: 'select 1'
